- name: Create Jenkins slave
  hosts: localhost
  vars:
    jenkins_url: "http://localhost:8080"
    jenkins_user: "admin"
    jenkins_token: "11a60d0059efd55317827d3477a5d041b3"
    slave_config_file: "requirements.json"
    jenkins_node: "mynew"
  tasks:
    - name: Ensure slave configuration file is present
      ansible.builtin.copy:
        src: "{{ slave_config_file }}"
        dest: "/Users/tanushreerakshit/.jenkins/workspace/ansible"
    - name: Create Jenkins slave node
      uri:
        url: "{{jenkins_url}}/computer/doCreateItem?name={{ jenkins_node }}&type=hudson.slaves.DumbSlave"
        method: POST
        user: "admin"
        password: "11a60d0059efd55317827d3477a5d041b3"
        force_basic_auth: yes
        body_format: json
        body:
         name: "ansible-slave"
         type: "hudson.slaves.DumbSlave$DescriptorImpl"
         json: "{{ lookup('file', '/Users/tanushreerakshit/.jenkins/workspace/ansible/{{ slave_config_file }}') }}"
        status_code: 200  # Define the expected status code if necessary
        validate_certs: no  # Adjust as needed based on your Jenkins setup
      register: result
