- hosts: localhost
  vars:
    jenkins_url: "http://localhost:8080"
    admin_username: "admin"
    api_token: "11a60d0059efd55317827d3477a5d041b3"
    agent_name: "ansible-agent"
    agent_config_json: |
      {
        "numExecutors": "2",
        "remoteFS": "/home/jenkins",
        "labelString": "ansible-agent",
        "mode": "NORMAL",
        "launcher": {
          "stapler-class": "hudson.slaves.JNLPLauncher",
          "$class": "hudson.slaves.JNLPLauncher"
        },
        "retentionStrategy": {
          "stapler-class": "hudson.slaves.RetentionStrategy$Always",
          "$class": "hudson.slaves.RetentionStrategy$Always"
        },
        "nodeProperties": {
          "stapler-class-bag": "true",
          "hudson-slaves-EnvironmentVariablesNodeProperty": {},
          "hudson-tools-ToolLocationNodeProperty": {},
          "stapler-class": "hudson.model.DescriptorList",
          "$class": "hudson.model.DescriptorList"
        }
      }

  tasks:
    - name: Create Jenkins Agent
      ansible.builtin.shell: >
        curl -X POST \
          -u "{{ admin_username }}:{{ api_token }}" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "name={{ agent_name }}" \
          --data-urlencode "type=hudson.slaves.DumbSlave\$DescriptorImpl" \
          --data-urlencode "json={{ agent_config_json }}" \
          "{{ jenkins_url }}/computer/doCreateItem"
      args:
        executable: /bin/bash
      register: curl_output

    - debug:
        var: curl_output
