- hosts: localhost
  vars:
    jenkins_url: "http://localhost:8080"
    admin_username: "admin"
    api_token: "11a60d0059efd55317827d3477a5d041b3"
    agent_config_file: :requirements.json" 
  tasks:
    - name: Create Jenkins slave node
      ansible.builtin.shell:
         curl -X POST \
         -u admin:11a60d0059efd55317827d3477a5d041b3 \
         -H Content-Type:application/x-www-form-urlencoded \
         --data-urlencode "name=ansible-agent" \
         --data-urlencode "type=hudson.slaves.DumbSlave\$DescriptorImpl" \
         --data-urlencode "json=@{{ agent_config_file }}" \
         http://localhost:8080/computer/doCreateItem
    - debug:
        var: result
