- hosts: localhost
  vars:
    jenkins_url: "http://localhost:8080"
    admin_username: "admin"
    api_token: "11a60d0059efd55317827d3477a5d041b3"
    slave_config_file: "requirements.json"

  tasks:
    - name: Create Jenkins slave node
      ansible.builtin.uri:
        url: "{{ jenkins_url }}/manage/computer/doCreateItem"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
          Authorization: "Basic {{ (admin_username + ':' + api_token) | b64encode }}"
        body_format: form-urlencoded
        body:
          name: "ansible-slave"
          type: "hudson.slaves.DumbSlave$DescriptorImpl"
          json: "{{ lookup('file', '/Users/tanushreerakshit/.jenkins/workspace/ansible/{{ slave_config_file }}') }}"
      register: result

    - debug:
        var: result
