- name: Create Jenkins Slave Node
  hosts: localhost
  tasks:
    - name: Create Jenkins Node
      ansible.builtin.uri:
        url: "{{ jenkins_url }}/computer/doCreateItem?name=mynew&type=hudson.slaves.DumbSlave"
        method: POST
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
      register: result

    - debug:
        var: result
