#lookup() method is actually used to look at resources outside of host system running ansible i.e either remote systems or vaults and instead
#lookup() ,ansible_env should be used to fetch jenkins env vars or credentials if jenkins master and ansible is running in same machine
#but ansible_env is failing to fetch jenkins api token.

---
- hosts: localhost
  tasks:
   - name: print JENKINS API TOKEN token using lookup()
     debug:
       msg: "Jenkins id is {{lookup('env','jenkins-admin-api-token')}}"
   - name: print JENKINS ID using lookup
     debug:
        msg: "Jenkins id {{lookup('env','linux_un_pass')}}"
   - name: print JENKINS ENVIRONMENT VARIABLE using lookup()
     debug:
        msg: "jenkins var {{lookup('env','BUILD_NAME')}}"
   - name: print JENKINS ENVIRONMENT VARIABLE using ansible_env
     debug:
      msg: "Jenkins api token using ansible.env {{ansible_env.BUILD_NUMBER}}"
