---
- hosts: localhost
  tasks:
   - name: print jenkins api token
     debug:
       msg: "Jenkins id is {{lookup('env','jenkins-admin-api-token')}}"
   - name: print jenkins ID
     debug:
        msg: "Jenkins id {{lookup('env','linux_un_pass'}}"
