---
- name: Retrieve secret from HashiCorp Vault using lookup plugin
  hosts: localhosts
  vars:
    secret_username: "{{ lookup('hashi_vault', 'secret=secret/data/jenkins token=00000000-0000-0000-0000-000000000000 url=http://127.0.0.1:8200') }}"
  tasks:
    - name: Print retrieved username
      debug:
        msg: "Print Hashi user {{ secret_username }}"
