- name: Example Playbook
  hosts: all
  tasks:
    - name: Retrieve a secret from Vault
      uri:
        url: "http://127.0.0.1:8200/ui/vault/secrets/secret/kv/jenkins/details?version=2"
        method: GET
        headers:
          Authorization: "Bearer {{ lookup('env', 'my_hashi_vault') }}"
        return_content: yes
      register: vault_response

    - name: Parse the secret from Vault response
      set_fact:
        secret_value: "{{ vault_response.json.data.data.secret_key }}"

    - name: Show the secret value
      debug:
        msg: "The secret value is {{ secret_value }}"


