---
- name: Retrieve secret from HashiCorp Vault using lookup plugin
  hosts: localhosts
  vars:
    secret_username: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/jenkins, 'linux-username', url='http://127.0.0.1:8200', token='00000000-0000-0000-0000-000000000000') }}"
  tasks:
    - name: Print retrieved username
      debug:
        msg: "Print Hashi user {{ secret_username }}"
