- name: Example Playbook
  hosts: localhost
  tasks:
    - name: Retrieve a secret from Vault
      debug:
        msg: "{{ lookup('hashivault', 'secret/data/jenkins', token=lookup('env', 'my_hashi_vault')) }}"
