---
- name: Create Jenkins Agent Node
  hosts: localhost
  vars:
    jenkins_url: "http://localhost:8080"
    admin_username: "admin"
    api_token: "{{ lookup('hashi_vault', 'secret/jenkins/jenkins-api-token field=token') }}"
    slave_config_file: "requirements.json"

  tasks:
    - name: Create Jenkins agent node
      ansible.builtin.uri:
        url: "{{ jenkins_url }}/computer/doCreateItem"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
          Authorization: "Basic {{ (admin_username + ':' + api_token) | b64encode }}"
        body_format: form-urlencoded
        body:
          name: "ansible-agent2"
          type: "hudson.slaves.DumbSlave$DescriptorImpl"
          json: "{{ lookup('file', slave_config_file) }}"
        follow_redirects: true
      register: result

    - debug:
        var: result
