---
- name: Retrieve secrets from HashiCorp Vault
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve secret from Vault
      uri:
        url: "http://127.0.0.1:8200/ui/vault/secrets/secret/kv/jenkins/details?version=2"
        method: GET
        headers:
          X-Vault-Token: "{{ lookup('env', 'VAULT_TOKEN') }}"
        return_content: yes
        status_code: 200
      register: vault_response

    - name: Set username and password facts
      set_fact:
        username: "{{ vault_response.json.data.data.username }}"
        password: "{{ vault_response.json.data.data.password }}"

    - name: Print retrieved secrets
      debug:
        msg: |
          Username: {{ username }}
          Password: {{ password }}
