---
- name: Retrieve secrets from HashiCorp Vault
  hosts: localhosts
  gather_facts: no
  tasks:
    - name: Retrieve secret from Vault
      uri:
        url: "http://127.0.0.1:8200/ui/vault/secrets/secret/kv/jenkins/details?version=2"
        method: GET
        headers:
          X-Vault-Token: "{{ lookup('env', 'VAULT_TOKEN') }}"
        return_content: yes
        status_code: 200
      register: vault_response

    - name: Extract secrets from response
      set_fact:
        username_linux: "{{ vault_response.json.data.data['linux-username'] }}"

    - name: Print retrieved secrets
      debug:
        msg: |
          Username: {{ username_linux }}
