---
- name: Retrieve username from Vault
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Debug raw Vault data (KV v2)
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/data/jenkins:jenkins-admin-username') }}" 
        
    


       
