---
- name: Test HashiCorp Vault Lookup
  hosts: webservers
  gather_facts: no
  tasks:
    - name: Test HashiCorp Vault Lookup
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/data/jenkins field=username-linux') }}"
