---
- name: Test HashiCorp Vault Lookup
  hosts: localhost
  gather_facts: no
  vars:
    jenkins_url: "http://localhost:8080"
    secret_username: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/jenkins field=username-linux') }}"
    secret_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/jenkins field=password-linux') }}"
    slave_config_file: "requirements.json"

  tasks:
    - name: Print Jenkins username
      debug:
        msg: "Jenkins username is {{ secret_username }}"

    - name: Print Jenkins password
      debug:
        msg: "Jenkins password is {{ secret_password }}"
