---
- name: Retrieve secrets from HashiCorp Vault
  hosts: localhost
  gather_facts: no
  vars:
    admin_username: "admin"
    api_token: "11f6d1065b82b7f6cbb1962ca8302d02b6"
  tasks:
    - name: Retrieve secret from Vault
      uri:
        url: "http://127.0.0.1:8200/v1/secret/data/jenkins"
        method: GET
        headers:
          X-Vault-Token: "{{ lookup('env', 'VAULT_TOKEN') }}"
        return_content: yes
        status_code: 200
      register: vault_response

    - name: Set username and password facts
      set_fact:
        username: "{{ vault_response.json.data.data.username }}"
        password: "{{ vault_response.json.data.data.password }}"

    - name: Print retrieved secrets
      debug:
        msg: |
          Username: {{ username }}
          Password: {{ password }}
