---
- name: Retrieve username from Vault
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Debug raw Vault data (KV v2)
      debug:
        msg:  "{{ lookup('hashi_vault', 'secret['jenkins-admin-username']= my.secret/data/jenkins', token='00000000-0000-0000-0000-000000000000', url='http://127.0.0.1:8200') }}"


       
