---
- name: Test HashiCorp Vault Lookup
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Test HashiCorp Vault Lookup
      debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/jenkins field=username-linux') }}"
