---
- name: Retrieve secrets from HashiCorp Vault
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve secret from Vault
      community.hashi_vault.hashi_vault:
        url: "{{ lookup('env', 'VAULT_ADDR') }}"
        token: "{{ lookup('env', 'VAULT_TOKEN') }}"
        secret: "secret/data/jenkins"
      register: vault_response

    - name: Debug full vault response
      debug:
        var: vault_response

    - name: Set username fact
      set_fact:
        username: "{{ vault_response['data']['data']['username'] | default('undefined') }}"

    - name: Print retrieved username
      debug:
        msg: "Username: {{ username }}"
