---
- name: Retrieve secret from Vault
  hosts: localhost
  vars:
    vault_token: "00000000-0000-0000-0000-000000000000"
  tasks:
    - name: Read a secret from HashiCorp Vault
      community.hashi_vault.vault_read:
        url: http://127.0.0.1:8200
        token: "{{ vault_token }}"
        secret: secret/jenkins
      register: vault_secret

    - name: Show the retrieved secret
      debug:
        msg: "The value of the secret is {{ vault_secret.data.value }}"

