---
- name: Retrieve secret from Vault
  hosts: localhost
  tasks:
    - name: Read a secret from HashiCorp Vault
      community.hashi_vault.vault_read:
        url: http://127.0.0.1:8200
        token: "{{ VAULT_TOKEN }}"
        secret: secret/my-secret
      register: vault_secret

    - name: Show the retrieved secret
      debug:
        msg: "The value of the secret is {{ vault_secret.data.value }}"

