---
- name: Retrieve secret from HashiCorp Vault
  hosts: localhost
  gather_facts: no
  vars:
    vault_token: "00000000-0000-0000-0000-000000000000"
    vault_url: "http://127.0.0.1:8200"
    secret_path: "secret/jenkins"

  tasks:
    - name: Read a secret from HashiCorp Vault
      ansible.builtin.uri:
        url: "{{ vault_url }}/v1/{{ secret_path }}"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        return_content: yes
      register: response

    - name: Show the retrieved secret
      debug:
        msg: "The value of the secret is {{ response.json.data.value }}"


