- name: Test community.general.uri module
  hosts: localhost
  tasks:
    - name: Fetch content from example.com
      ansible.builtin.uri:
        url: http://127.0.0.1:8200/ui/vault/auth?with=token
        method: GET
      register: result

    - name: Show result
      debug:
        msg: "{{ result }}"
