{
  "name": "ansible-slave",
  "nodeDescription": "Jenkins slave created by Ansible",
  "numExecutors": 1,
  "remoteFS": "/home/jenkins",
  "labels": "ansible",
  "launcher": {
    "stapler-class": "hudson.slaves.JNLPLauncher",
    "$class": "hudson.slaves.JNLPLauncher"
  },
  "retentionStrategy": {
    "stapler-class": "hudson.slaves.RetentionStrategy$Always",
    "$class": "hudson.slaves.RetentionStrategy$Always"
  },
  "nodeProperties": {
    "stapler-class-bag": "true",
    "$class": "hudson.model.Hudson$MasterComputer"
  }
}
