---
- name: Create Jenkins Agent Node
  hosts: localhost
  vars:
    jenkins_url: "http://localhost:8080"
    admin_username: "admin"
    api_token: "11f6d1065b82b7f6cbb1962ca8302d02b6"
    slave_config_file: "working_req.json"

  tasks:
    - name: Return all kv v2 secrets from a path
       debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/data/jenkins', token='00000000-0000-0000-0000-000000000000', url='http://127.0.0.1:8200') }}"
        
    - name: Create Jenkins agent node
      ansible.builtin.uri:
        url: "{{ jenkins_url }}/computer/doCreateItem"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
          Authorization: "Basic {{ (admin_username + ':' + api_token) | b64encode }}"
        body_format: form-urlencoded
        body:
          name: "ansible-agent2"
          type: "hudson.slaves.DumbSlave$DescriptorImpl"
          json: "{{ lookup('file', slave_config_file) }}"
        follow_redirects: true
      register: result

    - debug:
        var: result
